[HLS-3448] Content type other http
helios/opentelemetry-go-contrib pull request #12
Opened 2023-02-28 14:15 UTC by nata7che

2023-02-28 14:18 UTC, nozik requested changes

2023-02-28 14:18 UTC, nozik commented on instrumentation/github.com/gorilla/mux/otelmux/mux.go
>  	obfuscator "github.com/helios/go-sdk/data-obfuscator"
Can we add this logic to the obfuscator (perhaps rename it) to avoid all this code duplication?

2023-02-28 15:59 UTC, nozik requested changes

2023-02-28 15:59 UTC, nozik commented on instrumentation/github.com/gorilla/mux/otelmux/mux.go
> +				shouldSkipContentByType, _ := datautils.ShouldSkipContentCollectionByContentType(respContentType)
Probably more efficient to avoid this calculation unless metadataonly is false

2023-02-28 15:59 UTC, nozik commented on instrumentation/github.com/labstack/echo/otelecho/echo.go
> +		shouldSkipContentByType, _ := datautils.ShouldSkipContentCollectionByContentType(w.contentType)
Same

2023-02-28 15:59 UTC, nozik commented on instrumentation/github.com/labstack/echo/otelecho/echo.go
> +				shouldSkipContentByType, _ := datautils.ShouldSkipContentCollectionByContentType(respContentType)
Same

2023-02-28 15:59 UTC, nozik commented on instrumentation/net/http/otelhttp/transport.go
>  		if !wb.metadataOnly && !shouldSkipContentByType {
same

2023-02-28 15:59 UTC, nata7che commented on instrumentation/github.com/gorilla/mux/otelmux/mux.go
> +				shouldSkipContentByType, _ := datautils.ShouldSkipContentCollectionByContentType(respContentType)
not sure I understood your meaning

2023-02-28 16:00 UTC, nata7che commented on instrumentation/github.com/gorilla/mux/otelmux/mux.go
> +				shouldSkipContentByType, _ := datautils.ShouldSkipContentCollectionByContentType(respContentType)
you mean add it inside the `!metadataOnly` and add another `if`?

2023-02-28 16:01 UTC, nozik commented on instrumentation/github.com/gorilla/mux/otelmux/mux.go
> +				shouldSkipContentByType, _ := datautils.ShouldSkipContentCollectionByContentType(respContentType)
You can do it in the same line of `!metadatOnly`

2023-03-01 07:56 UTC, nozik approved these changes

2023-03-01 08:16 UTC, merged